name: Publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v7
      - run: |
          make specs
          mv site public
      - uses: actions/git-pages@v2
        with:
          site: https://${{ forgejo.event.repository.owner.username }}.codeberg.page/${{ forgejo.event.repository.name }}/
          token: ${{ forgejo.token }}
          source: public/
